### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by shivanshsinghal107**
Added function to get you the country list the bot has the data for & modified get_stock_price() function such that now it gives stock price of all indices the bot has for a country. Also now you can give any country name you want along with the /index command, it is not bound to have only one argument.
For Eg: /index South Korea, /index Hong Kong, etc.

### CODE REVIEW

**Comment by high-in-entropy** [comment]
This is great! Can you work for adding more countries to the list? This is optional and will not take much time, just changing the `*.csv` file. Anyway, we have the option to improve the list in later versions as well. Now let's work on improving, adding new features!

**Comment by shivanshsinghal107** [comment]
> This is great! Can you work for adding more countries to the list? This is optional and will not take much time, just changing the `*.csv` file. Anyway, we have the option to improve the list in later versions as well. Now let's work on improving, adding new features!

Definitely, I am gonna add more countries as well as top indices of existing countries. And just tell me what feature you want in the bot, I will do it whenever I get time.

**Comment by high-in-entropy** [comment]
> > This is great! Can you work for adding more countries to the list? This is optional and will not take much time, just changing the `*.csv` file. Anyway, we have the option to improve the list in later versions as well. Now let's work on improving, adding new features!
> 
> Definitely, I am gonna add more countries as well as top indices of existing countries. And just tell me what feature you want in the bot, I will do it whenever I get time.

Additions to next version :
* send the price chart (graphs) along with `/index` function.
* latest financial news from a list of orgs - *economist, the FT, CNBC, Bloomberg*
* commodity prices just like `/index`. Commodities - oil, gold, etc.

**Comment by shivanshsinghal107** [comment]
> > > This is great! Can you work for adding more countries to the list? This is optional and will not take much time, just changing the `*.csv` file. Anyway, we have the option to improve the list in later versions as well. Now let's work on improving, adding new features!
> > 
> > 
> > Definitely, I am gonna add more countries as well as top indices of existing countries. And just tell me what feature you want in the bot, I will do it whenever I get time.
> 
> Additions to next version :
> 
> * send the price chart (graphs) along with `/index` function.
> * latest financial news from a list of orgs - _economist, the FT, CNBC, Bloomberg_
> * commodity prices just like `/index`. Commodities - oil, gold, etc.

Commodity thing done, now you can get the commodity list the bot has the data for by command /commlist and bot can get you the commodity price by command /comm "commodity name".

**Comment by high-in-entropy** [comment]
That is great! Try changing `/comm` to `/commodity` instead. Send a PR.

**Pull request merged**
